name: "Terraform pipeline"

on:
  push:
    paths:
      - "**.tf"
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Setup terraform"
        uses: hashicorp/setup-terraform@v4

      - name: "Run terraform"
        run: |
          terraform init
          terraform plan
          terraform apply -auto-approve

      - name: Powiadomienie na discord
        if: success()
        run: |
          curl -H  "Content-Type: application/json" \
          -d '{"content": "**SUKCES** - Terraform został poprawnie zainicjalizowany i wdrożony"}' \
          ${{ secrets.DC_WEBHOOK }}

      - name: Powiadomienie na discord (Błąd)
        if: failure()
        run: |
          curl -H  "Content-Type: application/json" \
          -d '{"content": "**BŁĄD** - Wdrożenie terraforma nie powiodło się."}' \
          ${{ secrets.DC_WEBHOOK }}
